name: HunterHomeStaging
favicon: null
layout_spectrum: 0.5061563835479319
typography_spectrum: 0.9757338049821556
title: 'Hunter Home Staging & Design'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.42974326643161476
  lightness: 0.35941042355261743
  saturation: 0.19971567089669406
  rhythmicContrast: 0.8166552840266377
purpose: []
