typography_spectrum: 1
color:
  brandColors:
    - '#a9aeb6'
    - '#ffffff'
    - '#797f8a'
    - '#f9b36e'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: HunterHomeStaging
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Hunter Home Staging & Design
description: Staging homes to sell since 2007
purpose: []
