typography_spectrum: 1
color:
  brandColors:
    - '#a9aeb6'
    - '#ffffff'
    - '#797f8a'
    - '#f9b36e'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: HunterHomeStaging
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Hunter Home Staging & Design
    url: 'http://www.hunterstaging.com'
    type: external
  - name: About
    id: 35717270-7870-488e-948b-436e3e37ab44
    type: content
  - name: Services
    id: 659e9b76-1633-410f-b104-fd44b5ac6f48
    type: content
  - name: Gallery
    id: 66b4802c-3d0e-4c85-88ef-c3d84fde3a13
    type: content
  - name: Contact
    id: 8777ed05-d0b5-4a74-a9e9-295ca9821f38
    type: content
favicon: null
title: Hunter Home Staging & Design
description: Staging homes to sell since 2007
purpose: []
