name: HunterHomeStaging
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9757338049821556
title: Hunter Home Staging
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a9aeb6'
    - '#ffffff'
    - '#797f8a'
    - '#f9b36e'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
